{{- if .Values.envs -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.prefixName" . }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/scaleio
data:
  {{- range $key,$value := .Values.envs -}}
  {{- $base64value := b64enc (toString $value) -}}
  {{ printf "%s: %s" $key $base64value | nindent 2 }}
  {{- end }}
{{- end }}