apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.account | toString }}:role/{{ include "chart.prefixName" . }}
  name: {{ include "chart.prefixName" . }}
  namespace: {{ .Release.Namespace }}
